kind: pipeline
type: docker
name: default

steps:
  - name: inspection
    image: shirasagi/cibase:ruby-265-chrome-77
    commands:
      - uname -a
      - cat /etc/debian_version
      - date
      - locale
      - mongo --version
      - mongo --host mongo --eval "db.version()"
      - ruby --version
      - google-chrome --version
      - df -h | fgrep -i shm
    volumes:
      - name: cache
        path: /var/cache/shirasagi
      - name: droneshm
        path: /dev/shm
      - name: docker.sock
        path: /var/run/docker.sock

  - name: config/mongoid.yml
    image: shirasagi/cibase:ruby-265-chrome-77
    commands:
      - cp -n config/samples/mongoid.yml config/
      - sed -i 's/localhost:27017/mongo:27017/g' config/mongoid.yml
      - cat config/mongoid.yml

  - name: config/secrets.yml
    image: shirasagi/cibase:ruby-265-chrome-77
    commands:
      - cp -n config/samples/secrets.yml config/
      - cat config/secrets.yml

  - name: config/webmail
    image: shirasagi/cibase:ruby-265-chrome-77
    commands:
      - cp -n config/defaults/webmail.yml config/
      - sed -i 's/#\ test_by:\ user/test_by:\ user/g' config/webmail.yml
      - sed -i 's/#\ test_user:/test_user:/g' config/webmail.yml
      - sed -i 's/#\ \ \ host:\ localhost/\ \ host:\ mail/g' config/webmail.yml
      - sed -i 's/#\ \ \ account:\ email/\ \ account:\ email/g' config/webmail.yml
      - sed -i 's/#\ \ \ password:\ pass/\ \ password:\ pass/g' config/webmail.yml
      - cat config/webmail.yml

  - name: config/voice.yml
    image: shirasagi/cibase:ruby-265-chrome-77
    commands:
      - cp -n config/defaults/voice.yml config/
      - sed -i 's#/usr/local/bin/sox#/usr/bin/sox#g' config/voice.yml
      - sed -i 's#/usr/local/bin/lame#/usr/bin/lame#g' config/voice.yml
      - cat config/voice.yml

  - name: bundle
    image: shirasagi/cibase:ruby-265-chrome-77
    volumes:
      - name: cache
        path: /var/cache/shirasagi
      - name: docker.sock
        path: /var/run/docker.sock
    commands:
      - bundle install --path=/var/cache/shirasagi/bundle

  - name: rspec
    image: shirasagi/cibase:ruby-265-chrome-77
    volumes:
      - name: cache
        path: /var/cache/shirasagi
      - name: droneshm
        path: /dev/shm
      - name: docker.sock
        path: /var/run/docker.sock
    environment:
      sandbox: 1
      allow_open_jtalk: 1
      ldap_host: 153.122.23.169
      CI: true
      DRONE: true
    commands:
      - bundle check --path=/var/cache/shirasagi/bundle
      - bundle exec rspec spec/features/gws
      # - bundle exec rspec spec/features/gws/report
      # - bundle exec rspec spec/features/gws/roles_spec.rb
      # - bundle exec rspec spec/features/gws/schedule
      # - bundle exec rspec spec/features/gws/share
      # - bundle exec rspec spec/features/gws/sites_spec.rb
      # - bundle exec rspec spec/features/gws/staff_record
      # - bundle exec rspec spec/features/gws/survey
      # - bundle exec rspec spec/features/gws/user_profiles_spec.rb
      # - bundle exec rspec spec/features/gws/user_titles_spec.rb
      # - bundle exec rspec spec/features/gws/users_spec.rb
      # - bundle exec rspec spec/features/gws/workflow

services:
  - name: mongo
    image: mongo:3.4
    command: [ --smallfiles, --logpath=/dev/null ]
    ports:
      - 27017
  - name: test_mail
    image: shirasagi/mail
    ports:
      - 143
      - 587

volumes:
  - name: cache
    host:
      path: /tmp/cache/drone-shirasagi
  - name: droneshm
    temp: {}
  - name: docker.sock
    host:
      path: /var/run/docker.sock
