language: ruby
rvm:
  - 2.1.2

services:
  - mongodb

bundler_args: "--without development"
install:
  - pushd .
  - sh .travis.d/install.sh
  - popd
before_script:
  - pushd .
  - sh .travis.d/before_script.sh
  - popd
