# MongoDB Configuration
# https://docs.mongodb.org/ecosystem/tutorial/mongoid-installation/#anatomy-of-a-mongoid-config

production:
  clients:
    default:
      database: ss
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: ss_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

development:
  clients:
    default:
      database: ss
      hosts:
        - localhost:27017
      options:
        #user: username
        #password: password

  # Configure Mongoid specific options. (optional)
  options:
