# gws

production: &production
  # Disable GWS.
  disable: false

  # Disable navigation
  disable_navi: false

  # StyleSheets on gws pages.
  stylesheets: ["gws/style"]

  # JavaScripts on gws pages.
  javascripts: ["gws/script"]

  history:
    save_days: 90
    severity: info
    severity_notice: disabled

  chorg:
    models: []
    exclude_fields:
      - "filename"
      - "state"
      - "/_state$/"
      - "md5"
      - "route"
      - "/_route$/"
      - "workflow_state"
      - "workflow_comment"
      - "url"
      - "/_url$/"
    ids_fields:
      - "_id"
      - "id"
    max_division: 3

test:
  <<: *production
  disable: false

development:
  <<: *production
  disable: false
