# gws

production: &production
  # Disable GWS.
  disable: false

  # Disable navigation
  disable_navi: false

  # StyleSheets on gws pages.
  stylesheets: ["gws/style"]

  # JavaScripts on gws pages.
  javascripts: ["gws/script"]

  history:
    save_days: 90
    severity: info
    severity_notice: disabled

test:
  <<: *production
  disable: false

development:
  <<: *production
  disable: false
