production: &production
  # specify which group should be logged in.
  login_group: シラサギ市

  # without csrf token ( /.mypage/remote_login )
  remote_login: false

  # Redirects the page after login.
  logged_in_page: /.mypage

test:
  <<: *production

development:
  <<: *production
