production: &production
  # Disable Webmail.
  disable: true

  # Default settings
  clients:
    default:
      # host
      host: localhost
      options:
        port: 143
      # auth_type: LOGIN, PLAIN, CRAM-MD5, DIGEST-MD5
      auth_type: LOGIN
      # user: uid, email
      account: email

  # Cache mails
  cache_mails: true

test:
  <<: *production
  disable: false

development:
  <<: *production
  disable: false
